import { InternshipAdd } from "@/feature"
import Head from "next/head"
import React from "react"

import { NavbarProfile } from "@/widgets"

const ProfilePage = () => {
	return (
		<>
			<Head>
				<title>My Applicationss</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<NavbarProfile />
			<InternshipAdd />
		</>
	)
}

export default ProfilePage
