import { InternshipList } from "@/feature"
import dynamic from "next/dynamic"
import Head from "next/head"

import { Footer, NavbarProfile } from "@/widgets"

const PublicRoute = dynamic(() => import("@/widgets/public-route"), {
	ssr: false,
})

const InternshipsPage = () => {
	return (
		<>
			<PublicRoute>
				<Head>
					<title>Freshman Careers</title>
					<meta name="description" content="Generated by create next app" />
					<meta name="viewport" content="width=device-width, initial-scale=1" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<NavbarProfile />
				<InternshipList />
				{/*<Responses />*/}
				<Footer />
			</PublicRoute>
		</>
	)
}

export default InternshipsPage
