import { InternshipList } from "@/feature"
import dynamic from "next/dynamic"
import Head from "next/head"

const PrivateRoute = dynamic(() => import("@/widgets/private-route"), {
	ssr: false,
})

const InternshipsPage = () => {
	return (
		<PrivateRoute>
			<Head>
				<title>Freshman Careers</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<InternshipList />
		</PrivateRoute>
	)
}

export default InternshipsPage
