import dynamic from "next/dynamic"
import Head from "next/head"

import { NavbarProfile } from "@/widgets"

const PublicRoute = dynamic(() => import("@/widgets/public-route"), {
	ssr: false,
})

const CompaniesPage = () => {
	return (
		<>
			<PublicRoute>
				<Head>
					<title>CompaniesPage</title>
					<meta name="description" content="Generated by create next app" />
					<meta name="viewport" content="width=device-width, initial-scale=1" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<NavbarProfile />
			</PublicRoute>
		</>
	)
}

export default CompaniesPage
