import { InternshipEdit } from "@/feature/internships/edit/ui"
import dynamic from "next/dynamic"
import Head from "next/head"
import React from "react"

const PrivateRoute = dynamic(() => import("@/widgets/private-route"), {
	ssr: false,
})

const EditInternship = () => {
	return (
		<PrivateRoute>
			<Head>
				<title>Internship add</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<InternshipEdit />
		</PrivateRoute>
	)
}

export default EditInternship
